import java.util.Random;
/**
 *  Computes some statistics about families in which the parents decide 
 *  to have children until they have at least one child of each gender.
 *  The program expects to get two command-line arguments: an int value
 * 	that determines how many families to simulate, and an int value
 *  that serves as the seed of the random numbers generated by the program.
 *  Example usage: % java OneOfEachStats 1000 1
 */
public class OneOfEachStats {
	public static void main (String[] args) {
		// Gets the two command-line arguments
		int T = Integer.parseInt(args[0]);
		int seed = Integer.parseInt(args[1]);
		// Initailizes a random numbers generator with the given seed value
        Random generator = new Random(seed);  

		int allChildren = 0;
		int families2 = 0;
		int families3 = 0;
		int families4 = 0;
		String common;
		
		for(int i=0;i<T;i++){

		String children = "";

		boolean boy = false;
		boolean girl = false;
		
		while (!(boy&&girl)) {

		int gender = (int)(generator.nextDouble()*2);

		if (gender==0) {
			children+="b";
			boy = true;
		} 
		else {
			children+="g";
			girl = true;
		}
			
		}	
		allChildren+=children.length();

		if(children.length()==2){
			families2++;
		} 
		else if(children.length()==3){
			families3++;
		} else{
			families4++;
		}

		}
		double average = (double)(allChildren)/T;

		int max = Math.max(families2,Math.max(families3, families4));

		if(max==families2){
			common = "2.";
		} else if(max==families3){
			common = "3.";
		} else{
			common = "4 or more.";
		}

		System.out.println("Average: " + average + " children to get at least one of each gender.");
		System.out.println("Number of families with 2 children: " + families2);
		System.out.println("Number of families with 3 children: " + families3);
		System.out.println("Number of families with 4 or more children: " + families4);
		System.out.println("The most common number of children is "+common);
		
		//// In the previous version of this program, you used a statement like:
		//// double rnd = Math.random();
		//// Where "rnd" is the variable that stores the generated random value.
		//// In this version of the program, replace this statement with:
		//// double rnd = generator.nextDouble();
		//// This statement will generate a random value in the range [0,1),
		//// just like you had in the previous version, except that the 
		//// randomization will be based on the given seed.
		//// This is the only change that you have to do in the program.
		    
	}
}
